name: Waka Readme

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update this repo's README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          REPOSITORY: davaded/davaded
          SHOW_TIME: true
          SHOW_TOTAL: true
          BLOCKS: ░▒▓█
          TIME_RANGE: all_time
          LANG_COUNT: 6
          SHOW_MASKED_TIME: false
